# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# change this line if you do not want to import all submodules:
axolotlclient.modules.all=true

# Mod Properties
version=3.1.4-alpha.1

maven_group=io.github.axolotlclient

archives_base_name=AxolotlClient

minecraft_120=1.20.1
minecraft_18=1.8.9
minecraft_cts8=1.16_combat-6
minecraft_121=1.21.1

mappings_18=1.8.9+build.27
mappings_cts8=1.16_combat-6+build.2
mappings_120=1.20.1+build.23
mappings_121=1.21.1+build.9

fabric_loader=0.16.14

fapi_120=0.92.2
fapi_121=0.116.0
fabric_cts8=0.42.0+1.16
osl=0.16.3

legacy_lwgjl3=1.2.5+1.8.9

config=3.0.7
